spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
            #uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://data-server   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
          predicates:
            - Path=/**          #断言，路径相匹配的进行路由
#  cloud:
#    gateway:
#      routes:
#        - id: test-gateway
#            uri: lb://backing-service:8088
#            predicates:
#              - Path=/aaaS
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eurekaServer/eureka/